### ISSUE TITLE
Log flooded

### ISSUE THREAD

**Issue by Element2** [Smanar/Domoticz-deCONZ#123] opened 2022-01-18 00:08 UTC
Vanilla Ubuntu headless server version 20.04.3 LTS
After upgrading Domoticz from Beta 13949 to Beta 14081 the Domoticz log is flooded with the lines below.
deCONZ still works in Domoticz, but high cpu.
When going back to 13949 the log is normal again..
(Zgateway is my name for deCONZ-bridge)

2022-01-18 00:57:31.950 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.000 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.000 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.050 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.050 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.100 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.100 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.151 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.151 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.201 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.201 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.251 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.251 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.301 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.301 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.351 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.351 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.402 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.402 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.452 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.452 (Zgateway) Releasing lock for 'Zgateway'
2022-01-18 00:57:32.502 (Zgateway) Acquiring lock for 'Zgateway'
2022-01-18 00:57:32.502 (Zgateway) Releasing lock for 'Zgateway'

**Comment by Smanar** [comment] 2022-01-18 09:49
I will make a try because I don't see this message on the python plugin, I realy have no clue where it s from.

**Comment by pipiche38** [comment] 2022-01-18 09:53
https://github.com/domoticz/domoticz/blob/24e7b76a0bb76f471117691a5328724516932695/hardware/plugins/Plugins.cpp#L110

**Comment by Smanar** [comment] 2022-01-18 09:59
Ha nice, thx, so it s probably a new issue caused by the python stuff.
No problem on my side, but have just tried on a window machine, I m searching more information.

**Comment by Smanar** [comment] 2022-01-20 15:10
Can you make a try with the version 14092 ?
It work on my side, under Raspbian (just an error message about request lib, solved with a reboot)

**Comment by Smanar** [comment] 2022-01-20 17:57
Ok, so I will open an issue on their github, I have no answer on the forum, I will probably need more information later.

**Comment by Element2** [comment] 2022-01-20 17:59
ok

**Comment by Smanar** [comment] 2022-01-21 16:38
Lol, ok I will close the issue on domoticz github

**Closed** 2022-02-23 16:42 UTC
