### ISSUE TITLE
Domoticz 2020.1 upgrade

### ISSUE THREAD

**Issue by Allras82** [Smanar/Domoticz-deCONZ#51] opened 2020-04-17 06:17 UTC
Hello,

After upgrade og domoticz,to 2020.1 it like that deconz does not follow "domoticz speed"
I often have to send command more times before the change end up with a reaction in deconz device!

This is both for timers, manual activated switches and events!

In domoticz LOG it does however looks like deconz/domoticz is sending commands, but the do not end with a reaction in the device!

Br
Allan

**Comment by Smanar** [comment] 2020-04-17 13:08
Ok, so you have restarted deconz too in same time ?
You are using device firmware update in deconz ?

I think the problem is from deconz, not domoticz, I think if you are trying with phoscon you will have same problems (if it's not already solved) ?

**Comment by Allras82** [comment] 2020-04-17 19:27
Yes I have tried restart of entire system several times. It didn't help.

Yes I have activated OTA in deconz... is this a problem?

Any suggestions to solve de deconz problem?

Br
Allan

**Comment by Smanar** [comment] 2020-04-17 20:16
If you restart deconz, it can start the update procedure for some forgotten devices.
Better to wait for it stabilize.

You can disable the OTA or just wait some hours.

You have the same problem on Phoscon ?

You have the GUI version or the headless ?

**Comment by Allras82** [comment] 2020-04-17 20:31
Iv did a couple of test with devices only at phoscon... yes it has the same problem. U stable and slow response time!

I'm on a GUI version at a rpi3 with conbeell

**Comment by Smanar** [comment] 2020-04-18 09:35
So 2 thing to check, the cpu usage on the machine with deconz, and can you show your network from deconz GUI pls ?

**Comment by Smanar** [comment] 2020-04-18 16:21
I have find it https://community.jeedom.com/t/lenteur-deconz/15980
It's a french forum, for him the problem was an ikea plug, it have removed it and all is fine after.

It's not after an application upgrade on his side.

**Comment by Allras82** [comment] 2020-04-18 18:17
It's not easy to get at good picture of the network.. it's a bit of a mess.

I will try to isolate some devices but turning them off... to see if this helps.

**Comment by Allras82** [comment] 2020-04-18 18:31
![Screenshot_20200418-202920_RaspManager](https://user-images.githubusercontent.com/54345732/79657271-60b7aa80-81b3-11ea-945a-e670afcfd5ee.jpg)
![Screenshot_20200418-202857_RaspManager](https://user-images.githubusercontent.com/54345732/79657340-657c5e80-81b3-11ea-8452-5d3929eb3847.jpg)


It seems like deconz are using a bit of resources... but still the overall load shouldn't be critical I guess.!

**Comment by Smanar** [comment] 2020-04-19 08:52
For me 30 % is too much for a raspberry 3, how many device have you ?
Just by curiosity on the GUI you haven't enabled the "LQI" button ? it write value on green connexion ?

**Comment by Allras82** [comment] 2020-04-20 11:57
The LQI is not active.
I have 71 nodes in my network at the moment.

Picture of my net:

![net_zigbee](https://user-images.githubusercontent.com/54345732/79749089-dbe1a380-830e-11ea-81e5-6b587ac54523.GIF)

**Comment by Allras82** [comment] 2020-04-20 11:58
Im not sure how to "read" the network... whats the dif. betwean the read and green connections? is the red one a problem?

**Comment by Smanar** [comment] 2020-04-20 13:31
It's just an indication.
And the network is meshed, so you can have a red line + a green one on the same device.

Green = better link quality, red less.

A device can work with a red line.

I realy don't have idea, perhaps make an issue on deconz github.
You have just upgraded domoticz or all your OS ?
You have the last deconz version ? 2.05.75 ?

For me 30% is too much for a raspberry 3, you have perhaps something blocking.
As you have probably changed nothing on software, an hardware test with circuit breaker will be usefull and fast. if you have only light.

**Comment by Allras82** [comment] 2020-04-21 06:13
Ok, thanks.
Yes im on deconz 2.05.75

Yes iv upgraded my domoticz to the latest 2020.1, and i feel it's since then the system have been slow reacting. But still its only deconz part.
That was why i thought i might be the dezonz plugin for domoticz, that were causing the lower system response... and of cause it make sense of the plugin need to be reviewed after an update for the domoticz. 
I was just taking a change to install the new domotics. (I was hoping for better support for "magic home" devices, but this was not the case, so flashed by tasmota instead, which works great)

Im not sure where to find the deconz LOG!!?


Anyhow thank you for your support so far :-)

**Comment by Smanar** [comment] 2020-04-21 07:23
I don't think it's the plugin, beause you have same problem using phoscon.
But it's realy strange as you haven't changed anything on deconz or on your hardware.

You can run deconz in debug mode, whith closing it and run it again using command line
>deCONZ --dbg-info=2 --dbg-zdp=1 --dbg-zcl=1 --db-aps=1 --dbg-http=0

But never send the log to a file, only console output, realy lot of data.

If you have something blocking I think you will have a debug line (identical) more than 1 time by second.

**Comment by Smanar** [comment] 2020-07-07 16:36
@Allras82 by curiosity, you have find the problem ?

**Comment by Allras82** [comment] 2020-07-07 19:43
Hi Smanar

I've fixed the problem by removing a Philips hue lamp away from deconz and instead connecting it at the original hue Bridge... now everything works fine.
Downside is that I now have two zigbee network running.
I have not yet tried to reconnect the hue lamp to deconz.

So actually I did not fixed the problem, but its removed 😉

Br.
Allan

**Comment by Allras82** [comment] 2020-07-07 19:44
So for me it fine to close issue, if no further details I can support with.

**Comment by Smanar** [comment] 2020-07-08 14:51
So the problem was from a device.

And yes, that would have been my next question ^^, if you have made the try with another bulb.

Because it's pity having 2 zigbee network instead of one bigger (for mesh)

**Closed** 2020-08-06 18:11 UTC
